<a href="https://colab.research.google.com/github/SMeghanaa/DATA-SCIENCE/blob/master/5-06-2020(class).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Numpy random

In [0]:
from numpy import random
print(random.randint(1,10))      #random integer between the range
print(random.rand())             #float number between 0-1

3
0.3761388356482136


In [0]:
print(random.randint(100,size=(3)),"\n")
print(random.randint(100,size=(3,4)),"\n")
print(random.randint(100,size=(3,4,2)))

[90 68 78] 

[[52  8  6 62]
 [91 11 85 83]
 [ 3 12 39 69]] 

[[[ 1 70]
  [26 95]
  [12 13]
  [46 26]]

 [[69 14]
  [30 80]
  [32 99]
  [58 62]]

 [[33  0]
  [49 17]
  [ 1 43]
  [69 50]]]


In [0]:
#printing n no of arrays
print(random.rand())
print(random.rand(3),"\n")
print(random.rand(2,3))


0.8465791456446398
[0.50431394 0.09213389 0.72309217] 

[[0.47299894 0.64927431 0.27072099]
 [0.30996824 0.64832172 0.87611704]]


In [0]:
a=random.randint(100,size=(3))
a

array([53, 45, 65])

In [0]:
random.choice(a)     #single element selection

65

In [0]:
random.choice([1,2,3,4,5],size=(4,4))      #generating array with a given shape and elements from the list

array([[1, 3, 2, 4],
       [4, 2, 2, 2],
       [2, 5, 5, 1],
       [3, 1, 4, 4]])

###Pandas
1. Data manipulation,analysis and  cleaning
2. Tabular data,unlabeled data

In [0]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'f':9}
data={"First":dict1,"Second":dict2}
g=pd.DataFrame(data)
f=pd.DataFrame(data,dtype=np.int32)
print(g,"\n",f)

   First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0 
    First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0


In [0]:
#simple dictionary-->DataFrame
d1={"name":["Elle","Steve","mike"],'Address':["hyd","blore","chd"]}
d1.index=np.arange(1,len(d1)+1)
df1=pd.DataFrame(d1)
df1

AttributeError: ignored

In [0]:
#using Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.5,23.6,34.5,67.3,89.5,97.2,65.4,45.7,32.1,19.8])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1     12.5       a
1        2     23.6       b
2        3     34.5       c
3        4     67.3       d
4        5     89.5       e
5        6     97.2       f
6        7     65.4       g
7        8     45.7       h
8        9     32.1       i
9       10     19.8       j

#selecting the data from a DataFrame
1. loc
2. iloc    #index based(rows)

In [0]:
df3["column2"]

0    12.5
1    23.6
2    34.5
3    67.3
4    89.5
5    97.2
6    65.4
7    45.7
8    32.1
9    19.8
Name: column2, dtype: float64

In [0]:
df3[["column2","column3"]]

column2 column3
0     12.5       a
1     23.6       b
2     34.5       c
3     67.3       d
4     89.5       e
5     97.2       f
6     65.4       g
7     45.7       h
8     32.1       i
9     19.8       j

In [0]:
df3.loc[:,"column1"]    #single column

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
#extracting multiple column values
df3.loc[0:5,["column1","column2"]]                  #rows 0 to 5 of column1 and column2
                                                #row or column names are a must

column1  column2
0        1     12.5
1        2     23.6
2        3     34.5
3        4     67.3
4        5     89.5
5        6     97.2

In [0]:
df3.iloc[1,:]                    #row and column index values should be given

column1       2
column2    23.6
column3       b
Name: 1, dtype: object

In [0]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

####Retrieving info of DataFrame

In [0]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [0]:
df3.shape

(10, 3)

In [0]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [0]:
df3.index

RangeIndex(start=0, stop=10, step=1)

###Viewing data from the DataFrame
1. head()
2. tail()
3. sample()

In [0]:
df3.head()    #extracts the first 5 rows of DataFrame by default

column1  column2 column3
0        1     12.5       a
1        2     23.6       b
2        3     34.5       c
3        4     67.3       d
4        5     89.5       e

In [0]:
df3.head(3)

column1  column2 column3
0        1     12.5       a
1        2     23.6       b
2        3     34.5       c

In [0]:
df3.tail()

column1  column2 column3
5        6     97.2       f
6        7     65.4       g
7        8     45.7       h
8        9     32.1       i
9       10     19.8       j

In [0]:
df3.sample()

column1  column2 column3
9       10     19.8       j

In [0]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  48.760000
std     3.02765  29.633997
min     1.00000  12.500000
25%     3.25000  25.725000
50%     5.50000  40.100000
75%     7.75000  66.825000
max    10.00000  97.200000

In [0]:
df3.rename(columns={"column1":"first","column2":"second","column3":"third"})
df3

column1  column2 column3
0        1     12.5       a
1        2     23.6       b
2        3     34.5       c
3        4     67.3       d
4        5     89.5       e
5        6     97.2       f
6        7     65.4       g
7        8     45.7       h
8        9     32.1       i
9       10     19.8       j